[package]
name = "clay"
version = "0.0.1"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

description = "OpenCL ray/path tracer"
homepage = "https://github.com/nthend/clay"
repository = "https://github.com/nthend/clay"

keywords = ["ray-tracing", "path-tracing", "opencl"]
categories = ["graphics", "rendering", "multimedia"]

readme = "README.md"
build = "build.rs"

[dependencies]
ocl = "0.19"
ocl-include = "0.3.3"
nalgebra = "0.18"
rand = "0.7"
lazy_static = "1.3.0"
regex = "1"
uuid = { version = "0.7", features = ["v4"] }

clay-core = { git = "https://github.com/clay-rs/clay-core.git", rev = "2e08f9cc78f8f0657faa7c94b8fd038cde35ebeb" }
#clay-core = { path = "../clay-core" }

[build-dependencies]
walkdir = "2"

[dev-dependencies]
clay-viewer = { git = "https://github.com/clay-rs/clay-viewer.git", rev = "0a41f502486641f107f729005dc3b68975e979a7" }
#clay-viewer = { path = "../clay-viewer" }
