[package]
name = "clay"
version = "0.0.1"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

description = "OpenCL ray/path tracer"
homepage = "https://github.com/nthend/clay"
repository = "https://github.com/nthend/clay"

keywords = ["ray-tracing", "path-tracing", "opencl"]
categories = ["graphics", "rendering", "multimedia"]

readme = "README.md"
build = "build.rs"

[dependencies]
clay-core = { git = "https://github.com/clay-rs/clay-core.git", rev = "28867d2d708042b3f88986c351ebe34a2f3cf0ee" }
#clay-core = { path = "../clay-core" }

ocl = "0.19"
ocl-include = "0.3.3"
nalgebra = "0.18"
rand = "0.7"
lazy_static = "1.3.0"
regex = "1"

[build-dependencies]
walkdir = "2"

[dev-dependencies]
clay-viewer = { git = "https://github.com/clay-rs/clay-viewer.git", rev = "9b1b47e1f6c04318662131df44bc9434dda7c10f" }
#clay-viewer = { path = "../clay-viewer" }
